features_in_expected_order = ['domain_name', 'dns_has_dnskey', 'dns_A_count', 'dns_AAAA_count', 'dns_MX_count',
                              'dns_NS_count', 'dns_TXT_count', 'dns_SOA_count', 'dns_CNAME_count', 'dns_zone_level',
                              'dns_zone_digit_count',
                              'dns_zone_len', 'dns_zone_entropy', 'dns_resolved_record_types', 'dns_dnssec_score',
                              'dns_ttl_avg', 'dns_ttl_stdev', 'dns_ttl_low', 'dns_ttl_mid', 'dns_ttl_distinct_count',
                              'dns_soa_primary_ns_level', 'dns_soa_primary_ns_digit_count', 'dns_soa_primary_ns_len',
                              'dns_soa_primary_ns_entropy', 'dns_soa_email_level', 'dns_soa_email_digit_count',
                              'dns_soa_email_len', 'dns_soa_email_entropy', 'dns_soa_refresh', 'dns_soa_retry',
                              'dns_soa_expire', 'dns_soa_min_ttl', 'dns_domain_name_in_mx', 'dns_mx_avg_len',
                              'dns_mx_avg_entropy', 'dns_txt_avg_len', 'dns_txt_avg_entropy',
                              'dns_txt_external_verification_score', 'dns_txt_spf_exists', 'dns_txt_dkim_exists',
                              'dns_txt_dmarc_exists', 'ip_count', 'ip_mean_average_rtt', 'ip_v4_ratio',
                              'ip_a_aaaa_to_all_ratio', 'ip_entropy', 'ip_as_address_entropy', 'ip_asn_entropy',
                              'ip_distinct_as_count', 'tls_has_tls', 'tls_chain_len', 'tls_is_self_signed',
                              'tls_root_authority_hash', 'tls_leaf_authority_hash', 'tls_negotiated_version_id',
                              'tls_negotiated_cipher_id', 'tls_root_cert_validity_len', 'tls_leaf_cert_validity_len',
                              'tls_broken_chain', 'tls_expired_chain', 'tls_total_extension_count',
                              'tls_critical_extensions',
                              'tls_with_policies_crt_count', 'tls_percentage_crt_with_policies',
                              'tls_x509_anypolicy_crt_count', 'tls_iso_policy_crt_count',
                              'tls_joint_isoitu_policy_crt_count',
                              'tls_subject_count', 'tls_server_auth_crt_count', 'tls_client_auth_crt_count',
                              'tls_CA_certs_in_chain_ratio', 'tls_unique_SLD_count', 'tls_common_name_count',
                              'lex_name_len',
                              'lex_has_digit', 'lex_phishing_keyword_count', 'lex_benign_keyword_count',
                              'lex_consecutive_chars', 'lex_tld_len', 'lex_tld_abuse_score', 'lex_tld_hash',
                              'lex_sld_len',
                              'lex_sld_norm_entropy', 'lex_sld_digit_count', 'lex_sld_digit_ratio',
                              'lex_sld_phishing_keyword_count', 'lex_sld_vowel_count', 'lex_sld_vowel_ratio',
                              'lex_sld_consonant_count', 'lex_sld_consonant_ratio', 'lex_sld_non_alphanum_count',
                              'lex_sld_non_alphanum_ratio', 'lex_sld_hex_count', 'lex_sld_hex_ratio', 'lex_sub_count',
                              'lex_stld_unique_char_count', 'lex_begins_with_digit', 'lex_www_flag',
                              'lex_sub_max_consonant_len', 'lex_sub_norm_entropy', 'lex_sub_digit_count',
                              'lex_sub_digit_ratio', 'lex_sub_vowel_count', 'lex_sub_vowel_ratio',
                              'lex_sub_consonant_count',
                              'lex_sub_consonant_ratio', 'lex_sub_non_alphanum_count', 'lex_sub_non_alphanum_ratio',
                              'lex_sub_hex_count', 'lex_sub_hex_ratio', 'lex_phishing_bigram_matches',
                              'lex_phishing_trigram_matches', 'lex_phishing_tetragram_matches',
                              'lex_phishing_pentagram_matches', 'lex_malware_bigram_matches',
                              'lex_malware_trigram_matches',
                              'lex_malware_tetragram_matches', 'lex_dga_bigram_matches', 'lex_dga_trigram_matches',
                              'lex_dga_tetragram_matches', 'lex_avg_part_len', 'lex_stdev_part_lens',
                              'lex_longest_part_len',
                              'lex_short_part_count', 'lex_medium_part_count', 'lex_long_part_count',
                              'lex_superlong_part_count', 'lex_shortest_sub_len', 'lex_ipv4_in_domain',
                              'lex_has_trusted_suffix', 'lex_has_wellknown_suffix', 'lex_has_cdn_suffix',
                              'lex_has_vps_suffix',
                              'lex_has_img_suffix', 'lex_suffix_score', 'geo_countries_count', 'geo_continents_count',
                              'geo_malic_host_country', 'geo_lat_stdev', 'geo_lon_stdev', 'geo_mean_lat',
                              'geo_mean_lon',
                              'geo_min_lat', 'geo_max_lat', 'geo_min_lon', 'geo_max_lon', 'geo_lat_range',
                              'geo_lon_range',
                              'geo_centroid_lat', 'geo_centroid_lon', 'geo_estimated_area', 'geo_continent_hash',
                              'geo_countries_hash', 'rdap_registration_period', 'rdap_domain_age',
                              'rdap_time_from_last_change', 'rdap_domain_active_time', 'rdap_has_dnssec',
                              'rdap_registrar_name_len', 'rdap_registrar_name_entropy', 'rdap_registrar_name_hash',
                              'rdap_registrant_name_len', 'rdap_registrant_name_entropy', 'rdap_admin_name_len',
                              'rdap_admin_name_entropy', 'rdap_admin_email_len', 'rdap_admin_email_entropy',
                              'rdap_ip_v4_count', 'rdap_ip_v6_count', 'rdap_ip_shortest_v4_prefix_len',
                              'rdap_ip_longest_v4_prefix_len', 'rdap_ip_shortest_v6_prefix_len',
                              'rdap_ip_longest_v6_prefix_len', 'rdap_ip_avg_admin_name_len',
                              'rdap_ip_avg_admin_name_entropy',
                              'rdap_ip_avg_admin_email_len', 'rdap_ip_avg_admin_email_entropy',
                              
                               'html_create_element', 'html_write', 'html_char_code_at', 'html_concat', 'html_escape', 'html_eval', 'html_exec', 'html_from_char_code', 'html_link', 'html_parse_int', 
                               'html_replace', 'html_search', 'html_substring', 'html_unescape', 'html_add_event_listener', 'html_set_interval', 'html_set_timeout', 'html_push', 'html_index_of', 'html_document_write', 
                               'html_get', 'html_find', 'html_document_create_element', 'html_window_set_timeout', 'html_window_set_interval', 'html_hex_encoding', 'html_unicode_encoding', 'html_long_variable_name', 
                                'html_num_of_words', 'html_unique_words', 'html_average_word_len', 'html_num_of_lines', 'html_num_of_tags', 'html_num_of_paragraphs', 'html_num_of_divs', 
                               'html_num_of_titles', 'html_num_of_external_js', 'html_num_of_links', 'html_num_of_scripts', 'html_num_of_scripts_async', 'html_num_of_scripts_type',
                                'html_num_of_anchors', 'html_num_of_anchors_to_hash', 'html_num_of_anchors_to_https', 'html_num_of_anchors_to_com', 'html_num_of_inputs', 'html_num_of_input_password', 
                                'html_num_of_hidden_elements', 'html_num_of_input_hidden', 'html_num_of_objects', 'html_num_of_embeds', 'html_num_of_frame', 'html_num_of_iframe', 'html_num_of_iframe_src', 
                                'html_num_of_iframe_src_https', 'html_num_of_center', 'html_num_of_imgs', 'html_num_of_imgs_src', 'html_num_of_meta', 'html_num_of_links_href', 'html_num_of_links_href_https', 
                                'html_num_of_links_href_css', 'html_num_of_links_type', 'html_num_of_link_type_app', 'html_num_of_link_rel', 'html_num_of_all_hrefs', 'html_num_of_form_action', 'html_num_of_form_http', 
                                'html_num_of_strong', 'html_no_hrefs', 'html_internal_href_ratio', 'html_num_of_internal_hrefs', 'html_external_href_ratio', 'html_num_of_external_href', 'html_num_of_icon', 
                                'html_icon_external', 'html_num_of_form_php', 'html_num_of_form_hash', 'html_num_of_form_js', 'html_malicious_form', 'html_most_common', 'html_num_of_css_internal', 
                                'html_num_of_css_external', 'html_num_of_anchors_to_content', 'html_num_of_anchors_to_void', 'html_num_of_blank_spaces', 'html_blocked_keywords_label',

                                'rep_dn_virustotal_reputation', 'rep_dn_virustotal_malicious',
	                            'rep_dn_virustotal_suspicious', 'rep_dn_virustotal_undetected',
                                'rep_dn_virustotal_harmless', 'rep_dn_opentip_kaspersky_zone',
                                'rep_dn_opentip_kaspersky_category_green_zone_cnt',
                                'rep_dn_opentip_kaspersky_category_grey_zone_cnt',
                                'rep_dn_opentip_kaspersky_category_yellow_zone_cnt',
                                'rep_dn_opentip_kaspersky_category_orange_zone_cnt',
                                'rep_dn_opentip_kaspersky_category_red_zone_cnt',
                                'rep_dn_opentip_kaspersky_is_category_adware',
                                'rep_dn_opentip_kaspersky_is_category_phishing',
                                'rep_dn_opentip_kaspersky_is_category_malware',
                                'rep_dn_opentip_kaspersky_is_category_compromised',
                                'rep_dn_opentip_kaspersky_is_category_botnet_cnc',
                                'rep_dn_hybrid_analysis_malicious_cnt',
                                'rep_dn_hybrid_analysis_suspicious_cnt',
                                'rep_dn_hybrid_analysis_no_threat_cnt',
                                'rep_dn_hybrid_analysis_whitelisted_cnt',
                                'rep_dn_hybrid_analysis_worst_score',
                                'rep_dn_hybrid_analysis_best_score',
                                'rep_dn_hybrid_analysis_avg_score',
                                'rep_dn_hybrid_analysis_null_score_cnt',
                                'rep_dn_google_safe_browsing_unspecified_cnt',
                                'rep_dn_google_safe_browsing_malware_cnt',
                                'rep_dn_google_safe_browsing_social_engineering_cnt',
                                'rep_dn_google_safe_browsing_unwanted_software_cnt',
                                'rep_dn_google_safe_browsing_potentially_harmful_cnt',
                                'rep_dn_urlvoid_detection_cnt',
                                'rep_dn_cloudflare_malicious',
                                'rep_dn_fortiguard_spam',
                                'rep_dn_threatfox_malware_confidence_level',
                                'rep_dn_pulsedive_risk',
                                'rep_dn_pulsedive_risk_recommended',
                                'rep_dn_pulsedive_manual_risk',
                                'rep_ip_virustotal_avg_reputation',
                                'rep_ip_virustotal_avg_malicious',
                                'rep_ip_virustotal_avg_suspicious',
                                'rep_ip_virustotal_avg_undetected',
                                'rep_ip_virustotal_avg_harmless',
                                'rep_ip_opentip_kaspersky_green_zone_cnt',
                                'rep_ip_opentip_kaspersky_grey_zone_cnt',
                                'rep_ip_opentip_kaspersky_yellow_zone_cnt',
                                'rep_ip_opentip_kaspersky_orange_zone_cnt',
                                'rep_ip_opentip_kaspersky_red_zone_cnt',
                                'rep_ip_opentip_kaspersky_category_green_zone_cnt',
                                'rep_ip_opentip_kaspersky_category_grey_zone_cnt',
                                'rep_ip_opentip_kaspersky_category_yellow_zone_cnt',
                                'rep_ip_opentip_kaspersky_category_orange_zone_cnt',
                                'rep_ip_opentip_kaspersky_category_red_zone_cnt',
                                'rep_ip_opentip_kaspersky_category_adware_cnt',
                                'rep_ip_opentip_kaspersky_category_phishing_cnt',
                                'rep_ip_opentip_kaspersky_category_malware_cnt',
                                'rep_ip_opentip_kaspersky_category_compromised_cnt',
                                'rep_ip_opentip_kaspersky_category_botnet_cnc_cnt',
                                'rep_ip_hybrid_analysis_malicious_cnt',
                                'rep_ip_hybrid_analysis_suspicious_cnt',
                                'rep_ip_hybrid_analysis_no_threat_cnt',
                                'rep_ip_hybrid_analysis_whitelisted_cnt',
                                'rep_ip_hybrid_analysis_worst_score',
                                'rep_ip_hybrid_analysis_best_score',
                                'rep_ip_hybrid_analysis_avg_score',
                                'rep_ip_hybrid_analysis_null_score_cnt',
                                'rep_ip_google_safe_browsing_total_unspecified_cnt',
                                'rep_ip_google_safe_browsing_total_malware_cnt',
                                'rep_ip_google_safe_browsing_total_social_engineering_cnt',
                                'rep_ip_google_safe_browsing_total_unwanted_software_cnt',
                                'rep_ip_google_safe_browsing_total_potentially_harmful_cnt',
                                'rep_ip_nerd_max_score',
                                'rep_ip_project_honeypot_malicious_ratio',
                                'rep_ip_cloudflare_radar_malicious_ratio',
                                'rep_ip_abuseipdb_worst_score',
                                'rep_ip_abuseipdb_avg_score',
                                'rep_ip_abuseipdb_whitelisted_ratio',
                                'rep_ip_abuseipdb_tor_ratio',
                                'rep_ip_abuseipdb_total_reports',
                                'rep_ip_abuseipdb_avg_reports',
                                'rep_ip_fortiguard_spam_ratio',
                                'rep_ip_greynoise_noise_ratio',
                                'rep_ip_greynoise_riot_ratio',
                                'rep_ip_greynoise_total_benign',
                                'rep_ip_greynoise_total_malicious',
                                'rep_ip_criminalip_score_safe_cnt',
                                'rep_ip_criminalip_score_low_cnt',
                                'rep_ip_criminalip_score_moderate_cnt',
                                'rep_ip_criminalip_score_dangerous_cnt',
                                'rep_ip_criminalip_score_critical_cnt',
                                'rep_ip_threatfox_malware_ratio',
                                'rep_ip_threatfox_avg_confidence_level',
                                'rep_ip_pulsedive_risk_none_cnt',
                                'rep_ip_pulsedive_risk_low_cnt',
                                'rep_ip_pulsedive_risk_medium_cnt',
                                'rep_ip_pulsedive_risk_high_cnt',
                                'rep_ip_pulsedive_risk_critical_cnt',
                                'rep_ip_pulsedive_risk_retired_cnt',
                                'rep_ip_pulsedive_risk_unknown_cnt',
                                'rep_ip_pulsedive_manual_risk_ratio'
                              ]
